### ISSUE TITLE
在复现代码的过程中，发现loss=nan，排查发现是self.bert层的返回值存在nan值，请问您之前有遇到这个问题吗

### ISSUE THREAD

**Issue by uuuuuurrrrrr** [OStars/FLR-MRC#1]
在复现代码的过程中，发现loss=nan，排查发现是self.bert层的返回值存在nan值，请问您之前有遇到这个问题吗

**Comment by songxian1129** [comment]
你好，在测试集上怎么所有的指标都为0

**Comment by OStars** [comment]
我把代码 clone 下来运行了，并没有发现您说的这个问题，不知道您是如何执行代码的，简单来说只需要在项目根目录下执行 `bash run.sh` 就可以了

**Comment by uuuuuurrrrrr** [comment]
谢谢您的恢复，我不知道什么原因，我换了台服务器跑结果是正常的（除了文件路径什么都没改动），但在之前的服务器跑还是报nan，很离谱

**Comment by songxian1129** [comment]
你会出现best model: step 957, -- f1: 0.8741, p: 0.8882(4035/4543), r: 0.8605(4035/4689), total time: 86.88s
loading model from save_file/ccks2017_2_2_seed42_GAT_LR3E-5_epoch1/model.bin.
Creating features from dataset file at data
Saving features into cached file data/cached_pretrained_model_ccks2017_dev_uncased_512, total_records: 240, {'entity_cnt': 4689, 'max_token_len': 985}
Evaluation costs 7.891324996948242 seconds.
***** Eval results: dev *****
f1: 0.8741, p: 0.8882(4035/4543), r: 0.8605(4035/4689)
Creating features from dataset file at data
Saving features into cached file data/cached_pretrained_model_ccks2017_test_uncased_512, total_records: 3000, {'entity_cnt': 0, 'max_token_len': 1961}
Evaluation costs 33.63545036315918 seconds.
***** Eval results: test *****
f1: 0.0000, p: 0.0000(0/4600), r: 0.0000(0/0)
这种情况吗在测试集上怎么所有的指标都为0

**Comment by songxian1129** [comment]
> 谢谢您的恢复，我不知道什么原因，我换了台服务器跑结果是正常的（除了文件路径什么都没改动），但在之前的服务器跑还是报nan，很离谱

你好 你用的多大的服务器

**Comment by songxian1129** [comment]
> 谢谢您的恢复，我不知道什么原因，我换了台服务器跑结果是正常的（除了文件路径什么都没改动），但在之前的服务器跑还是报nan，很离谱

你好 你用的多大的服务器，是不是可以完整运行

**Comment by uuuuuurrrrrr** [comment]
可以完整运行 服务器大小我没观察过  不过我使用的是自己的数据集  没有出现您这种情况

**Comment by songxian1129** [comment]
> > 谢谢您的恢复，我不知道什么原因，我换了台服务器跑结果是正常的（除了文件路径什么都没改动），但在之前的服务器跑还是报nan，很离谱
> 
> 你好 你用的多大的服务器，是不是可以完整运行

好的 谢谢
