### ISSUE TITLE
你好，在测试集上怎么所有的指标都为0

### ISSUE THREAD

**Issue by songxian1129** [OStars/FLR-MRC#2]
你好，在测试集上怎么所有的指标都为0

**Comment by OStars** [comment]
您好，您使用的应该是 CMeEE 的测试集，这份测试集的结果是没有标签的，所以会得到 0 的结果，这份测试结果需要提交到 online judge 平台上才能进行评测 (不过我使用的 CMeEE v2，现在好像已经关闭评测入口了)

CCKS 2017 也是因为评测关闭了的原因，所以我们论文中报告的结果是验证集的结果，基线的结果也是在验证集上的结果

**Comment by songxian1129** [comment]
你好 ，我直接从天池中下载下来的，测试集没有标注实体，我可以直接把测试集去掉，通过验证集上的指标进行模型评估吗



在 2024-06-05 10:17:20，"OStars" ***@***.***> 写道：

您好，您使用的应该是 CMeEE 的测试集，这份测试集的结果是没有标签的，所以会得到 0 的结果，这份测试结果需要提交到 online judge 平台上才能进行评测 (不过我使用的 CMeEE v2，现在好像已经关闭评测入口了)

CCKS 2017 也是因为评测关闭了的原因，所以我们论文中报告的结果是验证集的结果，基线的结果也是在验证集上的结果

**Comment by OStars** [comment]
论文中的 CMeEE 结果是天池评估的结果，不过现在 CMeEE v2 是评不了了，您有两个方法可以备选：
1. 选择使用 CMeEE v3 的数据，天池现在开放了评估
2. 选择使用 v2 的验证集评估模型，不过这样的话您比较的基线也需要在验证集上进行评估

**Comment by songxian1129** [comment]
> 论文中的 CMeEE 结果是天池评估的结果，不过现在 CMeEE v2 是评不了了，您有两个方法可以备选：
> 
> 1. 选择使用 CMeEE v3 的数据，天池现在开放了评估
> 2. 选择使用 v2 的验证集评估模型，不过这样的话您比较的基线也需要在验证集上进行评估

好的谢谢，不过目前只看到CMeEE v2的数据集
